services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    environment:
      - TZ=${TZ}
    ports:
      - 8096:8096 # Jellyfin
      - 9696:9696 # Prowlarr
      - 7878:7878 # Radarr
      - 8989:8989 # Sonarr
      - 8080:8080 # qBittorrent
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
      - /var/run/tailscale:/var/run/tailscale

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/jellyfin:/config
      - ${ROOT}/cache:/cache
      - ${LFS}:/data
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
      - LOG_LEVEL=debug
      - LOG_HTML=true
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/prowlarr/data:/config
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${LFS}:/data # movies folder

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/sonarr/data:/config
      - ${LFS}:/data #optional
      - ${ROOT}/cache/sonarr:/cache

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ${ROOT}/config/qbittorrent/appdata:/config
      - ${LFS}/downloads:/downloads