services:
  nordvpn:
    build: ./nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    environment:
      - nord_vpn_token=${nord_vpn_token}
      - nord_vpn_server=${nord_vpn_server}
    restart: unless-stopped
    ports:
      - 8080:8080
    command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic
  
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped 

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/prowlarr/data:/config
    restart: unless-stopped
    ports:
      - 9696:9696

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/media/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/sonarr/data:/config
      - ${ROOT}/media/tvseries:/tv #optional
      - ${ROOT}/downloads:/downloads #optional
    restart: unless-stopped
    ports:
      - 8989:8989

  qbittorent:
    container_name: qbittorent
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    network_mode: service:nordvpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${qbittorent_webui_port}
    volumes:
      - ${ROOT}/config/qbittorent/appdata:/config
      - ${ROOT}/downloads:/downloads